machine: Update HDF_MACHINE reference name
Building kria starter kits fails with parse errors.

ERROR: Nothing PROVIDES 'virtual/hdf'
external-hdf PROVIDES virtual/hdf but was skipped: HDF_BASE and HDF_PATH must be specified.  See recipe for instructions.

This is due to HDF_MACHINE xsa name has changed in artifactory, Hence
update the HDF_MACHINE reference xsa name in starter kit machine conf
files.

Also update machine conf description.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>