kria-image-initramfs: Increase INITRAMFS_MAXSIZE
ERROR: kria-image-initramfs-1.0-r0 do_image_tar: The initramfs size 153088(K) exceeds INITRAMFS_MAXSIZE: 150000(K)

Appears that Scarthgap requires a bit more size then before.

Signed-off-by: Mark Hatle <mark.hatle@amd.com>