u-boot: Set CONFIG_BINMAN_DTB to empty
In 2025.01 u-boot BINMAN is enabled by default for Kria SOM, But in
yocto kria builds we EXT_DTB. Using both CONFIG_BINMAN_DTB and EXT_DTB
u-boot fails to build with below errors.

binman: Filename 'zynqmp-smk-k26-revA.dtb' not found in input path (.,/scratch/sandeep/yocto/2025.1/yp-dev-merge/build-zynqmp/tmp/work/k26_smk_kv-xilinx-linux/u-boot-xlnx/2025.01-xilinx-v2025.1+git/git,/scratch/sandeep/yocto/2025.1/yp-dev-merge/build-zynqmp/tmp/work/k26_smk_kv-xilinx-linux/u-boot-xlnx/2025.01-xilinx-v2025.1+git/git/board/xilinx/zynqmp,/scratch/sandeep/yocto/2025.1/yp-dev-merge/build-zynqmp/tmp/work/k26_smk_kv-xilinx-linux/u-boot-xlnx/2025.01-xilinx-v2025.1+git/recipe-sysroot/boot/devicetree//) (cwd='/scratch/sandeep/yocto/2025.1/yp-dev-merge/build-zynqmp/tmp/work/k26_smk_kv-xilinx-linux/u-boot-xlnx/2025.01-xilinx-v2025.1+git/build')
Wrote map file './fit-dtb.blob.map' to show errors
make[1]: *** [/scratch/sandeep/yocto/2025.1/yp-dev-merge/build-zynqmp/tmp/work/k26_smk_kv-xilinx-linux/u-boot-xlnx/2025.01-xilinx-v2025.1+git/git/Makefile:1135: .binman_stamp] Error 1
make[1]: Leaving directory '/scratch/sandeep/yocto/2025.1/yp-dev-merge/build-zynqmp/tmp/work/k26_smk_kv-xilinx-linux/u-boot-xlnx/2025.01-xilinx-v2025.1+git/build'
make: *** [Makefile:177: sub-make] Error 2
make: Leaving directory '/scratch/sandeep/yocto/2025.1/yp-dev-merge/build-zynqmp/tmp/work/k26_smk_kv-xilinx-linux/u-boot-xlnx/2025.01-xilinx-v2025.1+git/git'
ERROR: oe_runmake failed

If we are using u-boot EXT_DTB then we need to set CONFIG_BINMAN_DTB
to empty "" string which means using BINMAN is disabled for Kria SOM
devices.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>