bootbin-version-header.bbappend: Fix bootbin version string
The build for the kria petalinux sdt bsp failed because the version
was longer than the maximum length

ERROR: bootbin-version-header-1.0-r0 do_configure: version string too long

The machine name is lengthy (ex: xlnx-zynqmp-sm-k24-rev1)
Hence, machine name is included conditionally to be trimmed (ex: xlnx-sm-k24)
only if it is sdt and petalinux bsp flow to avoid this issue

Signed-off-by: John Vicky Vykuntapu <johnvicky.vykuntapu@amd.com>
Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>